### ISSUE TITLE
mac edge浏览器，油猴-该插件，夸克网盘无法批量重命名，不显示该按钮

### ISSUE THREAD

**Issue by leobba** [isaced/pan-naming-master#1]
![image](https://github.com/isaced/pan-naming-master/assets/62412113/f69f389a-91cd-45db-9efb-81335b9fe334)

mac edge浏览器，油猴-该插件，夸克网盘无法批量重命名，不显示该按钮

**Comment by isaced** [comment]
试了下 macOS Edge 也可以的，注意切换目录后需要刷新下页面，再勾选才会出现。
