### ISSUE TITLE
夸克网盘无法修改(最新版本)

### ISSUE THREAD

**Issue by Muyi2** [isaced/pan-naming-master#2]
夸克网盘无法修改，界面如下：
![image](https://github.com/isaced/pan-naming-master/assets/108456470/5713d844-9bba-4916-9cb4-7207bbea02ea)

**Comment by isaced** [comment]
夸克需要先勾选文件，不如果行尝试多刷新几次，后面会优化一下这个逻辑

**Comment by isaced** [comment]
增加了夸克未选中文件时的提示
