### ISSUE TITLE
windows浏览器失效

### ISSUE THREAD

**Issue by hhr114** [isaced/pan-naming-master#3]
Windows上的Edge和Chrome浏览器均已失效，刷新+多选也无法出现重命名按钮，恳请尽快修复~

**Comment by h025** [comment]
注意观察页面最最右上角 是否有一个蓝色的 里面放了一个锤子和扳手的按钮, 点它~

**Comment by h025** [comment]
> Windows上的Edge和Chrome浏览器均已失效，刷新+多选也无法出现重命名按钮，恳请尽快修复~

注意观察页面最最右上角 是否有一个蓝色的 里面放了一个锤子和扳手的按钮, 点它~
